#!/usr/bin/env python3
"""每周 star 巡检：批量刷新缓存 → 重建全部页面（gen_cards 内置毕业/徽章/报告）→ 可选开 Issue。

本地：python3 scripts/patrol.py            # 刷新 + 重建，打印报告
CI：  python3 scripts/patrol.py --issue    # 另把待裁决项写入 patrol 标签的 Issue

认证：本地走已登录的 gh；Actions 里由 GH_TOKEN 环境变量提供。
毕业线/下限与 gen_cards.py 保持一致（默认 1k–30k）。
"""
import json, os, subprocess, sys
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_cards import PROJECTS, CACHE, load_cache, fetch_repo

FIELDS = "stargazerCount pushedAt isArchived description"
REPORT = os.path.join(HERE, "data", "patrol-report.json")

def gql_batch(batch):
    parts = ", ".join(
        f'r{i}: repository(owner:"{r.split("/")[0]}", name:"{r.split("/")[1]}") {{ {FIELDS} }}'
        for i, r in enumerate(batch))
    q = "query { " + parts + " }"
    out = subprocess.run(["gh", "api", "graphql", "-f", "query=" + q],
                         capture_output=True, text=True)
    if out.returncode != 0:
        print("gh stderr:", out.stderr[:300])
        return None
    try:
        return json.loads(out.stdout)["data"]
    except Exception:
        return None

def main():
    cache = load_cache()
    repos = [p["r"] for p in PROJECTS]
    fresh = 0
    for i in range(0, len(repos), 25):
        batch = repos[i:i + 25]
        data = gql_batch(batch)
        for j, r in enumerate(batch):
            node = (data or {}).get(f"r{j}") or fetch_repo(r, cache)
            if node:
                cache[r] = node
                fresh += 1
    json.dump(cache, open(CACHE, "w"), indent=1)
    print(f"fetched {fresh}/{len(repos)} repos")

    # 停更检测：24 个月无推送（与页面 criteria 一致）
    cutoff = datetime.now(timezone.utc).timestamp() - 24 * 30.5 * 86400
    stale = []
    for p in PROJECTS:
        pu = (cache.get(p["r"]) or {}).get("pushedAt")
        if pu:
            ts = datetime.fromisoformat(pu.replace("Z", "+00:00")).timestamp()
            if ts < cutoff:
                stale.append(f'{p["r"]}: last push {pu[:10]} (>24 months, likely dormant)')

    r = subprocess.run([sys.executable, os.path.join(os.path.dirname(os.path.abspath(__file__)), "gen_cards.py")])
    if r.returncode != 0:
        sys.exit(r.returncode)

    rep = json.load(open(REPORT))
    rep["problems"] = rep.get("problems", []) + stale
    rep["fetched"] = fresh
    json.dump(rep, open(REPORT, "w"), indent=1)
    print("patrol report:", json.dumps(rep, ensure_ascii=False, indent=1)[:1500])
    if "--issue" in sys.argv:
        open_issue(rep)

def open_issue(rep):
    problems = rep.get("problems") or []
    if not problems:
        print("no problems — no issue needed")
        return
    body = ("Weekly star patrol found items needing a human call:\n\n"
            + "\n".join(f"- [ ] {p}" for p in problems)
            + "\n\n---\n_Auto-generated by the weekly patrol. For removals: delete the entry from"
              " `PROJECTS` in `scripts/gen_cards.py`, run the generator, push; then update/close this issue._")
    open("/tmp/patrol_body.md", "w").write(body)
    subprocess.run(["gh", "label", "create", "patrol", "--force"], capture_output=True)
    ex = subprocess.run(["gh", "issue", "list", "--label", "patrol", "--state", "open",
                         "--json", "number", "--limit", "1"], capture_output=True, text=True)
    nums = json.loads(ex.stdout or "[]") if ex.returncode == 0 else []
    if nums:
        subprocess.run(["gh", "issue", "edit", str(nums[0]["number"]), "--body-file", "/tmp/patrol_body.md"], check=False)
        print("updated patrol issue #" + str(nums[0]["number"]))
    else:
        subprocess.run(["gh", "issue", "create", "--title", "🤖 Star patrol: items needing review",
                        "--label", "patrol", "--body-file", "/tmp/patrol_body.md"], check=False)
        print("created patrol issue")

if __name__ == "__main__":
    main()
